# Setup
title:               Hanyu
tagline:             "Blog"
description:         "Hello! My name is Hanyu Tang. Welcome to my blog :)"
url:                 https://hanyutang-sandra.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Hanyu Tang
  url:               https://hanyutang-sandra.site
  email:             hanyutang.sandra@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
